### ISSUE TITLE
maintainer --check-programs, @PROGRAM_TEST

### ISSUE THREAD

**Issue by RYZENNAVI** [fubinf/sedrila#29]
## Configuration-Driven Program Testing System

A comprehensive program testing framework with YAML-based configuration has been implemented for SeDriLa.

### Main Features
- **`programchecker.yaml`**: Configuration file defining test strategies (skip programs, command overrides, partial skip rules)
- **Multi-command test parsing**: Extracts and validates multiple commands from `.prot` protocol files
- **`sedrila author --test-programs`**: Automated testing with parallel execution support
- **`sedrila author --test-programs <file>`**: Single program testing for targeted validation
- **Intelligent skip logic**: Auto-detects interactive programs, error demonstrations, dynamic output, and shell complexity

### Characteristics
- **Configuration sections**: Skip, Partial Skip, Command Override, Normal Test
- **Categorized reporting**: Failed tests with error details, skipped tests with reasons, passed tests with execution times
- **Output formats**: Console summary, JSON (`failed_tests`, `skipped_tests`, `passed_tests`), Markdown reports
- **Smart command extraction**: Handles Python scripts with arguments, Go programs, FastAPI applications
- **Comprehensive test coverage**: 16 pytest tests validating all functionality

Detailed changes and technical implementation are documented in **`docs/course_testing.md`** (section 2.2).

**Comment by prechelt** [comment]
`sedrila` is based on a **decentralized design** of SeDriLas: Tasks are specified in a mostly self-contained manner and depend on the centrally imposed structure of the course (chapters, taskgroups) only very little.
The authoring process is correspondingly decentralized as well. It is important to keep this up.

The automated testing is initially designed in a neccessarily centralized style: from the `sedrila` side.
But in the long run, the testing configuration has to be part of task design and must hence have a _decentralized_ form.

That means a (for instance) **yaml-based configuration** from the "outside" of the task markup is an acceptable approach, but **only at the task level**. This would be in line with the current structure, where a task already has multiple parts, most of which live in the `altdir` tree. Adding a test configuration file there (likely with a fixed suffix, say, `mytaskname.testconfig`) is the approach that has to be traded off against adding markup in existing files.

For this tradeoff, please keep in mind how **valuable locality** is: If I change the task, and change the instructor info for that task, it will be easier to update the testing configuration when it is right there in the existing parts rather than when it lives in yet another file.

_Do not let easier work during the development phase mislead you into a worse architecture for later actual use._
If you need to modify a small handful of tasks multiple times during development (in order to experiment with possible markup styles), you could do this on a git branch and it would not disturb the development of `propra-inf` a lot. If you pick tasks that have settled already (`stage: beta`), you will not even need to rebase that branch regularly and merging it will still be simple.

Depending on the details of that markup, **I tend to believe that markup in existing files is the better solution**.

**Comment by RYZENNAVI** [comment]
## Program Testing current situation
Currently, the **Programchecker**’s search mechanism mainly works by finding “test pairs”, that is, matching program files in **itree.zip** with corresponding `.prot` files in the **altdir** directory. If such a “test pair” is found and there are no specific markers in it, the system performs a normal test by default.

At present, 18 test pairs can be found: 6 of them can be tested normally without any markers, 2 (`go-interface` and `go-channels`) require using overrides, and 10 need to be completely skipped for manual testing. Since those 8 tests are correct and 10 are skipped, the overall test result shows as passed on local test and GitHub Actions.

The current issue is that for the remaining program files in **itree.zip** (a total of 81 files, minus the 18 test pairs, leaving 63 that cannot be tested), there are no corresponding `.prot` documents. I checked some of them and found that their command-line records are stored in Markdown files, for example, in **IDE-first-steps** and **py-Funktionale-Programmierung**. This might have been a relatively loose convention in the early stages.

From an architectural perspective, I suggest unifying the approach so that all collaborators write the command-line records separately as `.prot` files. What are your thoughts on this?

**Comment by RYZENNAVI** [comment]
## Program checking now in review
`--check-programs` and `--check-links` both belong to the maintainer subcommands, so I fixed the issue I previously encountered in `--check-links` while working on `--check-programs`. At this point, many aspects are similar to `--check-links`. I also rewrote the code style, docs, tests to align with the rest of sedrila’s code. I’m just not sure whether the current specification is acceptable.

Details in `maintainers.md` section 1-3 and 5

**Comment by RYZENNAVI** [comment]
## All the features discussed have been implemented
Details in `maintainers.md` section 5

**Comment by prechelt** [comment]
#### Single-container job

The fact that there is a `Maintainer-ProgramChecker-Multicontainer` job is laudable.
But given that, why does `Maintainer-ProgramChecker` still exist?

#### Report from Multicontainer job

The results of the 3 partial Multicontainer runs need to be merged into a single report rather than being three reports with lots of redundancy.
If something fails, we want to be able to quickly see which platforms succeed and which do not.

**Comment by RYZENNAVI** [comment]
## Multicontainer and Single-container

originally, Multicontainer is just an extension of Single-container across different environments such as Ubuntu and Debian, as well as different Python versions like 3.11-3.13. Single-container is what we actually needed in the first place. Functionally speaking, a single container is also sufficient.
However, your point here is good. We could keep only the multi-container version to continuously verify that `ProgramChecker `can run correctly across different environments.
But adjusting the report structure into a three-in-one format is probably more complex than expected, because the current multi-container version simply calls check-programs three times and concatenates the reports together.  
I will continue to consider how to adjust the report structure and refactor it after completing the final presentation.

**Comment by prechelt** [comment]
We would like to make sure your programs work across all environments our students might use.
Therefore, the Multi-Container is definitely useful.

**Comment by RYZENNAVI** [comment]
- removed the single-container job 
- merged the three matrix reports into one in a new merge-reports job, with a summary table at the top.

summary page: https://github.com/fubinf/propra-inf/actions/runs/28749095121
The reports are ordered by result type. If the Manual and Passed sections are identical across all environments, only one copy is shown. They are only displayed separately when differences occur between environments. 
What do you think?
